version: '3'
services:
  mysql:
    platform: linux/x86_64
    container_name: mysql-container
    image: 'mysql:latest'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './mysql-data-container:/var/lib/mysql'
